# Generated by Django 6.0.6 on 2026-06-27 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('admission_number', models.CharField(max_length=100, unique=True)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('physical_address', models.TextField(blank=True)),
                ('institution', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('year_of_study', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('training_mode', models.CharField(choices=[('PHYSICAL', 'Physical'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('session', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('WEEKEND', 'Weekend')], max_length=20)),
                ('attachment_company', models.CharField(blank=True, max_length=255)),
                ('attachment_supervisor', models.CharField(blank=True, max_length=255)),
                ('supervisor_phone', models.CharField(blank=True, max_length=20)),
                ('supervisor_email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_relationship', models.CharField(blank=True, max_length=100)),
                ('passport_photo', models.ImageField(upload_to='students/passports/')),
                ('id_copy', models.ImageField(upload_to='students/ids/')),
                ('introduction_letter', models.FileField(upload_to='students/letters/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_students', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
