# Generated by Django 6.0.6 on 2026-07-11 04:51

import students.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='introduction_letter',
            field=models.FileField(storage=students.storage.RawMediaCloudinaryStorage(), upload_to='students/letters/'),
        ),
    ]
