# Generated by Django 6.0.6 on 2026-07-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_introduction_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='introduction_letter',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
