# ==========================================================
# EXCEL REPORTS
# reports/excel_reports.py
# ==========================================================

from io import BytesIO

from django.http import HttpResponse
from django.utils import timezone

from openpyxl import Workbook
from openpyxl.styles import (
    Font,
    PatternFill,
    Border,
    Side,
    Alignment,
)
from openpyxl.utils import get_column_letter

from accounts.models import User
from attendance.models import (
    AttendanceSession,
    AttendanceRecord,
)
from assignments.models import (
    Assignment,
    AssignmentSubmission,
)


# ==========================================================
# COLORS
# ==========================================================

TITLE_FILL = PatternFill(
    fill_type="solid",
    fgColor="1F4E78"
)

HEADER_FILL = PatternFill(
    fill_type="solid",
    fgColor="D9EAD3"
)

SUMMARY_FILL = PatternFill(
    fill_type="solid",
    fgColor="FFF2CC"
)

WHITE_FONT = Font(
    color="FFFFFF",
    bold=True,
    size=16
)

HEADER_FONT = Font(
    bold=True
)

NORMAL_FONT = Font(
    size=11
)

THIN_BORDER = Border(
    left=Side(style="thin"),
    right=Side(style="thin"),
    top=Side(style="thin"),
    bottom=Side(style="thin"),
)


# ==========================================================
# CREATE WORKBOOK
# ==========================================================

def create_workbook(title):

    workbook = Workbook()

    sheet = workbook.active

    sheet.title = title

    return workbook, sheet


# ==========================================================
# MAIN TITLE
# ==========================================================

def write_title(sheet, title):

    sheet.merge_cells("A1:H1")

    cell = sheet["A1"]

    cell.value = title

    cell.font = WHITE_FONT

    cell.fill = TITLE_FILL

    cell.alignment = Alignment(
        horizontal="center",
        vertical="center"
    )

    sheet.row_dimensions[1].height = 28


# ==========================================================
# REPORT INFORMATION
# ==========================================================

def write_report_information(sheet, generated_by):

    sheet["A3"] = "Generated By"
    sheet["B3"] = generated_by

    sheet["A4"] = "Generated On"
    sheet["B4"] = timezone.localtime().strftime(
        "%d %B %Y %I:%M %p"
    )

    sheet["A3"].font = HEADER_FONT
    sheet["A4"].font = HEADER_FONT


# ==========================================================
# SUMMARY BOX
# ==========================================================

def write_summary(sheet, start_row, summary_data):

    row = start_row

    sheet.cell(
        row=row,
        column=1
    ).value = "Summary"

    sheet.cell(
        row=row,
        column=1
    ).font = HEADER_FONT

    sheet.cell(
        row=row,
        column=1
    ).fill = SUMMARY_FILL

    row += 1

    for label, value in summary_data:

        label_cell = sheet.cell(
            row=row,
            column=1
        )

        value_cell = sheet.cell(
            row=row,
            column=2
        )

        label_cell.value = label
        value_cell.value = value

        label_cell.font = HEADER_FONT

        label_cell.border = THIN_BORDER
        value_cell.border = THIN_BORDER

        row += 1

    return row


# ==========================================================
# TABLE HEADER
# ==========================================================

def write_table_header(
    sheet,
    row,
    headers
):

    for column, header in enumerate(
        headers,
        start=1
    ):

        cell = sheet.cell(
            row=row,
            column=column
        )

        cell.value = header

        cell.font = HEADER_FONT

        cell.fill = HEADER_FILL

        cell.alignment = Alignment(
            horizontal="center",
            vertical="center"
        )

        cell.border = THIN_BORDER


# ==========================================================
# TABLE ROW
# ==========================================================

def write_table_row(
    sheet,
    row,
    values
):

    for column, value in enumerate(
        values,
        start=1
    ):

        cell = sheet.cell(
            row=row,
            column=column
        )

        cell.value = value

        cell.font = NORMAL_FONT

        cell.border = THIN_BORDER


# ==========================================================
# AUTO SIZE COLUMNS
# ==========================================================

def auto_size_columns(sheet):

    for column_cells in sheet.columns:

        length = 0

        letter = get_column_letter(
            column_cells[0].column
        )

        for cell in column_cells:

            try:

                if cell.value:

                    length = max(
                        length,
                        len(str(cell.value))
                    )

            except Exception:

                pass

        sheet.column_dimensions[
            letter
        ].width = min(
            length + 5,
            40
        )


# ==========================================================
# RETURN EXCEL FILE
# ==========================================================

def download_workbook(
    workbook,
    filename
):

    output = BytesIO()

    workbook.save(output)

    output.seek(0)

    response = HttpResponse(
        output.getvalue(),
        content_type=(
            "application/vnd.openxmlformats-"
            "officedocument.spreadsheetml.sheet"
        )
    )

    response[
        "Content-Disposition"
    ] = f'attachment; filename="{filename}"'

    return response


# ==========================================================
# STUDENT REPORT EXCEL
# ==========================================================

def student_report_excel(request):
    """
    Export Student Report to Excel.
    Accessible to Super Admins and Trainers.
    """

    if not (
        request.user.is_staff or
        request.user.role in ["SUPER_ADMIN", "TRAINER"]
    ):
        return HttpResponse(
            "You are not authorized to access this report.",
            status=403
        )

    students = (
        User.objects
        .filter(role="STUDENT")
        .order_by("first_name", "last_name", "username")
    )

    workbook, sheet = create_workbook(
        "Student Report"
    )

    write_title(
        sheet,
        "CETMS STUDENT REPORT"
    )

    write_report_information(
        sheet,
        request.user.get_full_name() or request.user.username
    )

    # ======================================================
    # SUMMARY
    # ======================================================

    total_students = students.count()

    verified_students = students.filter(
        is_verified=True
    ).count()

    unverified_students = (
        total_students - verified_students
    )

    locked_accounts = students.filter(
        is_locked=True
    ).count()

    last_row = write_summary(
        sheet,
        6,
        [

            ("Total Students", total_students),

            ("Verified Students", verified_students),

            ("Unverified Students", unverified_students),

            ("Locked Accounts", locked_accounts),

        ]
    )

    # ======================================================
    # STUDENT TABLE
    # ======================================================

    table_row = last_row + 2

    headers = [

        "No",

        "Username",

        "Full Name",

        "Email",

        "Phone",

        "Verified",

        "Locked",

        "Date Joined",

    ]

    write_table_header(
        sheet,
        table_row,
        headers
    )

    row = table_row + 1

    for number, student in enumerate(
        students,
        start=1
    ):

        full_name = (
            student.get_full_name()
            if student.get_full_name()
            else student.username
        )

        write_table_row(

            sheet,

            row,

            [

                number,

                student.username,

                full_name,

                student.email,

                student.phone_number or "-",

                "Yes" if student.is_verified else "No",

                "Yes" if student.is_locked else "No",

                timezone.localtime(
                    student.date_joined
                ).strftime("%d/%m/%Y"),

            ]

        )

        row += 1

    auto_size_columns(sheet)

    return download_workbook(

        workbook,

        "Student_Report.xlsx"

    )

# ==========================================================
# ATTENDANCE REPORT EXCEL
# ==========================================================

def attendance_report_excel(request):
    """
    Export Attendance Report to Excel.
    Accessible to Super Admins and Trainers.
    """

    if not (
        request.user.is_staff or
        request.user.role in ["SUPER_ADMIN", "TRAINER"]
    ):
        return HttpResponse(
            "You are not authorized to access this report.",
            status=403
        )

    sessions = AttendanceSession.objects.count()

    records = (
        AttendanceRecord.objects
        .select_related(
            "student",
            "session"
        )
        .order_by(
            "-timestamp"
        )
    )

    workbook, sheet = create_workbook(
        "Attendance Report"
    )

    write_title(
        sheet,
        "CETMS ATTENDANCE REPORT"
    )

    write_report_information(
        sheet,
        request.user.get_full_name() or request.user.username
    )

    # ======================================================
    # SUMMARY
    # ======================================================

    total_records = records.count()

    present = records.filter(
        status="PRESENT"
    ).count()

    late = records.filter(
        status="LATE"
    ).count()

    absent = records.filter(
        status="ABSENT"
    ).count()

    active_sessions = AttendanceSession.objects.filter(
        is_active=True
    ).count()

    attendance_rate = 0

    if total_records > 0:

        attendance_rate = round(
            (present / total_records) * 100,
            1
        )

    last_row = write_summary(

        sheet,

        6,

        [

            ("Attendance Sessions", sessions),

            ("Active Sessions", active_sessions),

            ("Attendance Records", total_records),

            ("Present", present),

            ("Late", late),

            ("Absent", absent),

            ("Attendance Rate", f"{attendance_rate}%"),

        ]

    )

    # ======================================================
    # TABLE
    # ======================================================

    table_row = last_row + 2

    headers = [

        "No",

        "Student",

        "Course",

        "Session",

        "Status",

        "Recorded At",

        "Trainer",

    ]

    write_table_header(

        sheet,

        table_row,

        headers

    )

    row = table_row + 1

    for number, record in enumerate(
        records,
        start=1
    ):

        trainer = (
            record.session.created_by.get_full_name()
            or record.session.created_by.username
        )

        student = (
            record.student.get_full_name()
            or record.student.username
        )

        write_table_row(

            sheet,

            row,

            [

                number,

                student,

                record.session.course or "-",

                record.session.title,

                record.status,

                timezone.localtime(
                    record.timestamp
                ).strftime(
                    "%d/%m/%Y %H:%M"
                ),

                trainer,

            ]

        )

        row += 1

    auto_size_columns(sheet)

    return download_workbook(

        workbook,

        "Attendance_Report.xlsx"

    )

# ==========================================================
# ASSIGNMENT REPORT EXCEL
# ==========================================================

def assignment_report_excel(request):
    """
    Export Assignment Report to Excel.
    Accessible to Super Admins and Trainers.
    """

    if not (
        request.user.is_staff or
        request.user.role in ["SUPER_ADMIN", "TRAINER"]
    ):
        return HttpResponse(
            "You are not authorized to access this report.",
            status=403
        )

    assignments = Assignment.objects.all()

    submissions = (
        AssignmentSubmission.objects
        .select_related(
            "assignment",
            "student",
            "graded_by"
        )
        .order_by("-submitted_at")
    )

    workbook, sheet = create_workbook(
        "Assignment Report"
    )

    write_title(
        sheet,
        "CETMS ASSIGNMENT REPORT"
    )

    write_report_information(
        sheet,
        request.user.get_full_name() or request.user.username
    )

    # ======================================================
    # SUMMARY
    # ======================================================

    total_assignments = assignments.count()

    total_submissions = submissions.count()

    graded = submissions.filter(
        status="GRADED"
    ).count()

    pending = submissions.filter(
        status="SUBMITTED"
    ).count()

    late = submissions.filter(
        is_late=True
    ).count()

    last_row = write_summary(

        sheet,

        6,

        [

            ("Total Assignments", total_assignments),

            ("Total Submissions", total_submissions),

            ("Graded", graded),

            ("Pending Grading", pending),

            ("Late Submissions", late),

        ]

    )

    # ======================================================
    # TABLE HEADER
    # ======================================================

    table_row = last_row + 2

    headers = [

        "No",

        "Assignment",

        "Student",

        "Marks",

        "Percentage",

        "Status",

        "Late",

        "Submitted At",

        "Graded By",

    ]

    write_table_header(
        sheet,
        table_row,
        headers
    )

    # ======================================================
    # TABLE DATA
    # ======================================================

    row = table_row + 1

    for number, submission in enumerate(
        submissions,
        start=1
    ):

        grader = "-"

        if submission.graded_by:

            grader = (
                submission.graded_by.get_full_name()
                or submission.graded_by.username
            )

        student = (
            submission.student.get_full_name()
            or submission.student.username
        )

        marks = (
            submission.marks_awarded
            if submission.marks_awarded is not None
            else "-"
        )

        percentage = (
            f"{submission.percentage_score}%"
            if submission.marks_awarded is not None
            else "-"
        )

        write_table_row(

            sheet,

            row,

            [

                number,

                submission.assignment.title,

                student,

                marks,

                percentage,

                submission.status,

                "Yes" if submission.is_late else "No",

                timezone.localtime(
                    submission.submitted_at
                ).strftime(
                    "%d/%m/%Y %H:%M"
                ),

                grader,

            ]

        )

        row += 1

    auto_size_columns(sheet)

    return download_workbook(

        workbook,

        "Assignment_Report.xlsx"

    )

# ==========================================================
# ANALYTICS REPORT EXCEL
# ==========================================================

def analytics_report_excel(request):
    """
    Export overall CETMS analytics to Excel.
    Accessible only to Super Admins and Trainers.
    """

    if not (
        request.user.is_staff or
        request.user.role in ["SUPER_ADMIN", "TRAINER"]
    ):
        return HttpResponse(
            "You are not authorized to access this report.",
            status=403
        )

    workbook, sheet = create_workbook(
        "System Analytics"
    )

    write_title(
        sheet,
        "CETMS SYSTEM ANALYTICS REPORT"
    )

    write_report_information(
        sheet,
        request.user.get_full_name() or request.user.username
    )

    # ======================================================
    # USER STATISTICS
    # ======================================================

    total_users = User.objects.count()

    total_students = User.objects.filter(
        role="STUDENT"
    ).count()

    total_trainers = User.objects.filter(
        role="TRAINER"
    ).count()

    total_admins = User.objects.filter(
        role="SUPER_ADMIN"
    ).count()

    verified_users = User.objects.filter(
        is_verified=True
    ).count()

    locked_accounts = User.objects.filter(
        is_locked=True
    ).count()

    # ======================================================
    # ATTENDANCE STATISTICS
    # ======================================================

    attendance_sessions = AttendanceSession.objects.count()

    attendance_records = AttendanceRecord.objects.count()

    present = AttendanceRecord.objects.filter(
        status="PRESENT"
    ).count()

    late = AttendanceRecord.objects.filter(
        status="LATE"
    ).count()

    absent = AttendanceRecord.objects.filter(
        status="ABSENT"
    ).count()

    attendance_rate = 0

    if attendance_records > 0:

        attendance_rate = round(
            (present / attendance_records) * 100,
            2
        )

    # ======================================================
    # ASSIGNMENT STATISTICS
    # ======================================================

    assignments = Assignment.objects.count()

    submissions = AssignmentSubmission.objects.count()

    graded = AssignmentSubmission.objects.filter(
        status="GRADED"
    ).count()

    pending = AssignmentSubmission.objects.filter(
        status="SUBMITTED"
    ).count()

    late_submissions = AssignmentSubmission.objects.filter(
        is_late=True
    ).count()

    # ======================================================
    # SUMMARY
    # ======================================================

    summary = [

        ("Total Users", total_users),

        ("Students", total_students),

        ("Trainers", total_trainers),

        ("Administrators", total_admins),

        ("Verified Users", verified_users),

        ("Locked Accounts", locked_accounts),

        ("Attendance Sessions", attendance_sessions),

        ("Attendance Records", attendance_records),

        ("Attendance Rate", f"{attendance_rate}%"),

        ("Present", present),

        ("Late", late),

        ("Absent", absent),

        ("Assignments", assignments),

        ("Submissions", submissions),

        ("Graded", graded),

        ("Pending Grading", pending),

        ("Late Submissions", late_submissions),

    ]

    last_row = write_summary(
        sheet,
        6,
        summary
    )

    # ======================================================
    # SYSTEM STATUS
    # ======================================================

    row = last_row + 3

    sheet.cell(
        row=row,
        column=1
    ).value = "SYSTEM STATUS"

    sheet.cell(
        row=row,
        column=1
    ).font = HEADER_FONT

    sheet.cell(
        row=row,
        column=1
    ).fill = HEADER_FILL

    row += 1

    status_rows = [

        (
            "User Accounts",
            "Healthy" if total_users else "No Users"
        ),

        (
            "Attendance Module",
            "Operational"
        ),

        (
            "Assignment Module",
            "Operational"
        ),

        (
            "Overall System",
            "Running Normally"
        ),

    ]

    for item, value in status_rows:

        write_table_row(
            sheet,
            row,
            [item, value]
        )

        row += 1

    auto_size_columns(sheet)

    return download_workbook(
        workbook,
        "System_Analytics_Report.xlsx"
    )