# Generated by Django 6.0.6 on 2026-06-27 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255, unique=True)),
                ('min_attendance', models.FloatField(default=75)),
                ('min_evaluation', models.FloatField(default=60)),
                ('min_assignment', models.FloatField(default=60)),
                ('min_logbook', models.FloatField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('certificate_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('attendance_score', models.FloatField(default=0)),
                ('evaluation_score', models.FloatField(default=0)),
                ('assignment_score', models.FloatField(default=0)),
                ('logbook_score', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('grade', models.CharField(choices=[('DISTINCTION', 'Distinction'), ('CREDIT', 'Credit'), ('PASS', 'Pass'), ('FAIL', 'Fail')], default='FAIL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ISSUED', 'Issued'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
