# Generated by Django 6.0.6 on 2026-06-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentlogbook',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Student Logbook', 'verbose_name_plural': 'Student Logbooks'},
        ),
        migrations.AddField(
            model_name='studentlogbook',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentlogbook',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
