# Generated by Django 5.2.6 on 2026-07-11 18:23

import django.core.validators
import students.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_alter_studentlogbook_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlogbook',
            name='logbook_file',
            field=models.FileField(storage=students.storage.RawMediaCloudinaryStorage(), upload_to='logbooks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])]),
        ),
    ]
