# Generated by Django 6.0.6 on 2026-07-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_options_lesson_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to='lessons/recordings/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Google Meet, Zoom or Microsoft Teams link.', null=True),
        ),
    ]
