# Generated by Django 6.0.6 on 2026-07-02 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='opens_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
